export const colors = {
    ink: {
        lighter: '#6E707F',
        light: '#666878',
        base: '#383B50',
        dark: '#2B2D3D',
        darker: '#1B1D27',
        darkest: '#14151D',
    },
    sky: {
        lightest: '#F5F5F6',
        lighter: '#E3E3E4',
        light: '#DADACC',
        base: '#CFCFD1',
        dark: '#8D8D8E',
    },
    primary: {
        lightest: '#F8DFDD',
        lighter: '#ECA199',
        light: '#E6857B',
        base: '#DE6053',
        darkest: '#974138',
    },
    lavender: {
        lightest: '#F0E3F8',
        lighter: '#D4ABEA',
        light: '#C792E3',
        base: '#B671DB',
        darkest: '#7C4D95',
    },

    mellowApricot: {
        lightest: '#FCF0E2',
        lighter: '#F7D2A9',
        light: '#F5C48F',
        base: '#F2B36D',
        darkest: '#A57A4A',
    },
    blue: {
        lightest: '#DFE8FB',
        lighter: '#9FBCF3',
        light: '#82A7EF',
        base: '#5D8DEA',
        darkest: '#3F609F',
    },
    skyBlue: {
        lightest: '#DFF4FB',
        lighter: '#A0DDF3',
        light: '#83D3F0',
        base: '#5EC6EB',
        darkest: '#4087A0',
    },
    bdazzledBlue: {
        lightest: '#D5DDE7',
        lighter: '#8299B7',
        light: '#5D7BA1',
        base: '#2C5385',
        darkest: '#1E385A',
    },
    yellow: {
        lightest: '#FCF4DB',
        lighter: '#F7E094',
        light: '#F4D674',
        base: '#F1CA4A',
        darkest: '#A48932',
    },
    red: {
        lightest: '#FFE5E5',
        lighter: '#FF9898',
        light: '#FF6D6D',
        base: '#FF5247',
        darkest: '#D3180C',
    },
    facebook: {
        base: '#0078FF',
        dark: '#0067DB',
    },
    twitter: {
        base: '#1DA1F2',
        dark: '#0C90E1',
    },

    white: '#FFFFFF',
    black: '#000000',
    transparent: 'transparent',
};
